---
# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: inactivity
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  Note: The stale bot was recently added to this project to help weed out
  outdated issues. This will help us to focus time and energy on issues
  that are important and move the others out of the way.
  There could however be many issues that are still relevant
  but have gotten old without ever being fixed.
  As this is the first round of cleaning it might have been too eager.
  Feel free to re-open this issue if you think it deserves another look.
