version: '2'
services:
 transmission:
  image: doodlerx/transmission-openvpn
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  restart: always
  ports:
    - "9091:9091"
    - "8888:8888"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /your/storage/path/:/downloads
  environment:
    - OPENVPN_PROVIDER=PIA
    - OPENVPN_USERNAME=username
    - OPENVPN_PASSWORD=password
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - LOCAL_NETWORK=192.168.0.0/24
 proxy:
  image: doodlerx/transmission-openvpn-proxy
  links:
    - transmission
  ports:
    - 8080:8080
  volumes:
    - /etc/localtime:/etc/localtime:ro

 rss:
  image: doodlerx/transmission-rss
  links:
    - transmission
  environment:
    - RSS_URL=http://.../xxxxx.rss
